# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebCaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('web_case_title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('test_step_name', models.CharField(max_length=200)),
                ('locate_method', models.CharField(max_length=200)),
                ('element_value', models.CharField(max_length=200)),
                ('operate_method', models.CharField(max_length=200)),
                ('test_data', models.CharField(max_length=200)),
                ('asset_data', models.CharField(max_length=200)),
                ('web_case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.WebCaseList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
