# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='locate_method',
            field=models.IntegerField(choices=[(1, 'id'), (2, 'xpath')], default=1, verbose_name='元素定位方法'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='operate_method',
            field=models.IntegerField(choices=[(1, 'open_brower'), (2, 'open_url'), (3, 'send_keys'), (4, 'click')], default=4, verbose_name='操作方法'),
        ),
    ]
