# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20200629_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcasestep',
            name='order_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
