# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-30 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0004_auto_20200630_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='asset_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='element_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='test_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
