# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_auto_20200630_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcasestep',
            old_name='asset_data',
            new_name='assert_data',
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='operate_method',
            field=models.IntegerField(choices=[(1, 'open_brower'), (2, 'open_url'), (3, 'send_keys'), (4, 'click'), (5, 'switch_window'), (6, 'alert'), (7, 'switch_frame'), (8, 'switch_default_content'), (9, 'assert_text')], default=4, verbose_name='操作方法'),
        ),
    ]
