# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0006_auto_20200701_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('page_name', models.CharField(max_length=200)),
                ('element_name', models.CharField(max_length=200)),
                ('locate_method', models.IntegerField(choices=[(0, ''), (1, 'id'), (2, 'xpath'), (3, 'linktext'), (4, 'css_selector'), (5, 'class_name'), (6, 'name'), (7, 'tag_name')], default=0, verbose_name='元素定位方法')),
                ('element_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebPageOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('operation_name', models.CharField(max_length=200)),
                ('operate_method', models.IntegerField(choices=[(1, 'open_brower'), (2, 'open_url'), (3, 'send_keys'), (4, 'click'), (5, 'switch_window'), (6, 'alert'), (7, 'switch_frame'), (8, 'switch_default_content'), (9, 'assert_text'), (10, 'refresh'), (11, 'sleep'), (12, 'setup_login')], default=4, verbose_name='操作方法')),
                ('test_data', models.CharField(blank=True, max_length=200, null=True)),
                ('assert_data', models.CharField(blank=True, max_length=200, null=True)),
                ('order_num', models.IntegerField()),
                ('element_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.WebPageElements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='locate_method',
            field=models.IntegerField(choices=[(0, ''), (1, 'id'), (2, 'xpath'), (3, 'linktext'), (4, 'css_selector'), (5, 'class_name'), (6, 'name'), (7, 'tag_name')], default=0, verbose_name='元素定位方法'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='operate_method',
            field=models.IntegerField(choices=[(1, 'open_brower'), (2, 'open_url'), (3, 'send_keys'), (4, 'click'), (5, 'switch_window'), (6, 'alert'), (7, 'switch_frame'), (8, 'switch_default_content'), (9, 'assert_text'), (10, 'refresh'), (11, 'sleep'), (12, 'setup_login')], default=4, verbose_name='操作方法'),
        ),
    ]
